---
kind: pipeline
type: docker
name: amd64

steps:
  - name: build
    image: eclipse-temurin:11-jre-focal
    environment:
      GRADLE_USER_HOME: ~/.gradle
    commands:
      - ./gradlew checkScalafmtAll test
      - ./gradlew prepare
      - echo -n "1.1.$DRONE_BUILD_NUMBER,latest" > .tags
      - echo -n "1.1.$DRONE_BUILD_NUMBER" > ./docker/version

  - name: test Dockerfile
    image: plugins/docker
    settings:
      repo: eugenezadyra/luxmed-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/Dockerfile
      context: docker/
      dry_run: yes
    when:
      event:
        - pull_request

  - name: publish
    image: plugins/docker
    settings:
      repo: eugenezadyra/luxmed-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/Dockerfile
      context: docker/
    when:
      branch: master
      event: push


---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: eclipse-temurin:11-jre-focal
    environment:
      GRADLE_USER_HOME: ~/.gradle
    commands:
      - ./gradlew prepare
      - echo -n "1.1.$DRONE_BUILD_NUMBER-arm64,latest-arm64" > .tags
      - echo -n "1.1.$DRONE_BUILD_NUMBER" > ./docker/version

  - name: test Dockerfile
    image: plugins/docker
    settings:
      repo: eugenezadyra/luxmed-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/Dockerfile
      context: docker/
      dry_run: yes
    when:
      event:
        - pull_request

  - name: publish
    image: plugins/docker
    settings:
      repo: eugenezadyra/luxmed-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/Dockerfile
      context: docker/
    when:
      branch: master
      event: push

  - name: deploy_and_restart
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: digitalocean_host
      username:
        from_secret: digitalocean_user
      key:
        from_secret: digitalocean_key
      script:
        - cd ~/luxmed-bot
        - docker-compose down || true
        - rm -f docker-compose.yml
        - wget https://raw.githubusercontent.com/dyrkin/luxmed-booking-service/master/docker/docker-compose-arm64.yml -O docker-compose.yml
        - docker-compose pull
        - docker-compose up -d
    when:
      branch: master
      event: push